version: '1.1'
services:
  nginx:
    hostname: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - php:php-cgi
    volumes:
      - ./wwwroot:/usr/local/nginx/html
 
  php:
    hostname: php
    build: ./php
    links:
      - mysql:mysql-db
    volumes:
      - ./wwwroot:/usr/local/nginx/html
 
  mysql:
    hostname: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
  
  redis-server:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always

  node:
    hostname: node
    build:
      context: ./wwwroot
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - mysql:mysql-db
      - redis-server:rd
    command: node server/server.js
    volumes:
      - ./wwwroot:/wwwroot
    restart: always